import { createEnv } from "@t3-oss/env-core";
import { config } from "dotenv";
import fs from "fs";
import openapiTS, { astToString } from "openapi-typescript";
import path from "path";
import { z } from "zod";

import { API_DEFAULT_BASE_URL, API_VERSION_PATH } from "~/api/const";

config();

const env = createEnv({
  server: {
    API_BASE_URL: z.string().default(API_DEFAULT_BASE_URL),
    OUTPUT_FILE: z.string().default("src/api/schema.ts"),
  },
  runtimeEnvStrict: {
    API_BASE_URL: process.env.API_BASE_URL,
    OUTPUT_FILE: process.env.OUTPUT_FILE,
  },
});

const HEADER = `/**
 * This file was generated by codegen/openapi.ts
 * Do not edit this file manually.
 */

/* eslint-disable */
/* prettier-ignore */

`;

export async function main() {
  const url = `${env.API_BASE_URL}/${API_VERSION_PATH}/openapi.json`;
  const ast = await openapiTS(url);
  const code = astToString(ast);
  await fs.promises.writeFile(
    path.join(import.meta.dirname, "..", env.OUTPUT_FILE),
    HEADER + code
  );
}

void main();
