/**
 * This file was generated by codegen/openapi.ts
 * Do not edit this file manually.
 */

 

import type { components } from "./schema";

export type PoolAsset = components["schemas"]["PoolAsset"]
export type PartialPoolAsset = components["schemas"]["PartialPoolAsset"]
export type PoolAudit = components["schemas"]["PoolAudit"]
export type PoolStats = components["schemas"]["PoolStats"]
export type Pool = components["schemas"]["Pool"]
export type GetPoolsResponse = components["schemas"]["GetPoolsResponse"]
export type BaseError = components["schemas"]["BaseError"]
export type BadRequestError = components["schemas"]["BadRequestError"]
export type ValidatationFieldError = components["schemas"]["ValidatationFieldError"]
export type ValidationError = components["schemas"]["ValidationError"]
export type InternalServerError = components["schemas"]["InternalServerError"]
export type GetRecentPoolsResponse = components["schemas"]["GetRecentPoolsResponse"]
export type RecentPoolsSortBy = components["schemas"]["RecentPoolsSortBy"]
export type TopTradedPoolsInterval = components["schemas"]["TopTradedPoolsInterval"]
